SELECT
    c.CAR_ID,
    c.CAR_TYPE,
    Floor(30 * c.DAILY_FEE * (1 - 0.01 * d.DISCOUNT_RATE)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
ON d.CAR_TYPE = c.CAR_TYPE
    AND d.DURATION_TYPE = '30일 이상'
WHERE (c.CAR_TYPE = '세단' OR c.CAR_TYPE = 'SUV')
    AND 30 * c.DAILY_FEE * (1 - 0.01 * d.DISCOUNT_RATE) >= 500000
    AND 30 * c.DAILY_FEE * (1 - 0.01 * d.DISCOUNT_RATE) < 2000000
    AND c.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30'
       AND END_DATE >= '2022-11-01'
    )
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC