SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT(o.USER_ID)) AS USERS
FROM ONLINE_SALE o
JOIN USER_INFO i
ON o.USER_ID = i.USER_ID
WHERE i.GENDER is not null
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC
