-- ANIMAL_INS 보호소에 들어온 동물의 정보
-- ANIMAL_OUTS 입양 보낸 동물의 정보
SELECT 
    o.ANIMAL_ID,
    o.NAME
FROM ANIMAL_OUTS o LEFT JOIN ANIMAL_INS i
ON o.ANIMAL_ID = i.ANIMAL_ID
WHERE i.ANIMAL_ID IS null;

# SELECT * FROM ANIMAL_INS; 