WITH RENTAL_DURATION AS (
    SELECT
        h.HISTORY_ID,
        c.DAILY_FEE,
        DATEDIFF(h.END_DATE, h.START_DATE) + 1 AS DURATION,
        CASE 
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE NULL 
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    JOIN CAR_RENTAL_COMPANY_CAR c ON h.CAR_ID = c.CAR_ID
    WHERE c.CAR_TYPE = '트럭'
)

SELECT
    rd.HISTORY_ID,
    ROUND(rd.DURATION * rd.DAILY_FEE * (1 - 0.01 * COALESCE(d.DISCOUNT_RATE, 0))) AS FEE
FROM RENTAL_DURATION rd
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d ON rd.DURATION_TYPE = d.DURATION_TYPE AND d.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;