SELECT
    c.ITEM_ID,
    c.ITEM_NAME,
    c.RARITY
FROM ITEM_INFO p
JOIN ITEM_TREE t ON p.ITEM_ID = t.PARENT_ITEM_ID
JOIN ITEM_INFO c ON c.ITEM_ID = t.ITEM_ID
WHERE p.RARITY = 'RARE'
ORDER BY c.ITEM_ID DESC;