SELECT
    c.ID AS ID,
    c.GENOTYPE AS GENOTYPE,
    p.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA c
JOIN ECOLI_DATA p
  ON p.ID = c.PARENT_ID
WHERE (c.GENOTYPE & p.GENOTYPE) = p.GENOTYPE
ORDER BY c.ID ASC;