-- ANIMAL_INS : 동물의 정보 - 보호 시작일 DATETIME
-- ANIMAL_OUTS : 입양 보낸 동물의 정보 - 입양일 DATETIME
SELECT
    i.ANIMAL_ID,
    i.NAME
FROM ANIMAL_INS i, ANIMAL_OUTS o
WHERE i.ANIMAL_ID = o.ANIMAL_ID AND i.DATETIME > o.DATETIME
ORDER BY i.DATETIME ASC;

# SELECT * FROM ANIMAL_OUTS ORDER BY DATETIME ASC;