SELECT
    MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    AND EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY x
        WHERE x.CAR_ID = h.CAR_ID
            AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
        GROUP BY x.CAR_ID
        HAVING COUNT(*) >= 5
    )
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;