-- 코드를 작성해주세요
SELECT
    m.YEAR AS YEAR,
    (m.MAX_DEV - e.SIZE_OF_COLONY) AS YEAR_DEV,
    e.ID AS ID
FROM ECOLI_DATA e
JOIN (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_DEV
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) m
ON YEAR(e.DIFFERENTIATION_DATE) = m.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;