-- 코드를 입력하세요
SELECT
    DISTINCT c.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
ON h.CAR_ID = c.CAR_ID
WHERE CAR_TYPE = '세단'
AND START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY CAR_ID DESC;