# 물고기 종류 별
# 가장 큰 물고기
# 물고기의 ID에 대해 오름차순 정렬
SELECT
    f.ID,
    i.FISH_NAME,
    f.LENGTH
FROM FISH_INFO f
JOIN (SELECT 
        MAX(LENGTH) AS MAX_LENGTH,
        FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE) m ON m.MAX_LENGTH = f.LENGTH AND m.FISH_TYPE = f.FISH_TYPE
JOIN FISH_NAME_INFO i ON i.FISH_TYPE = f.FISH_TYPE
ORDER BY ID ASC
