SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD as B
JOIN USED_GOODS_REPLY as R
ON B.BOARD_ID = R.BOARD_ID
WHERE B.CREATED_DATE >= '2022-10-01' &&  B.CREATED_DATE < '2022-11-01'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;

# 1차 시도
# SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, CREATED_DATE
# FROM USED_GOODS_BOARD as B, USED_GOODS_REPLY as R
# WHERE B.CREATED_DATE >= '2022-10-01' &&  B.CREATED_DATE < '2022-11-01'
# ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;

# 2차 시도
# SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
# FROM USED_GOODS_BOARD as B, USED_GOODS_REPLY as R
# WHERE B.CREATED_DATE >= '2022-10-01' &&  B.CREATED_DATE < '2022-11-01'
# ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;