-- 코드를 입력하세요
SELECT
    b.CATEGORY,
    SUM(s.SALES) AS TOTAL_SALES
FROM BOOK_SALES s
JOIN BOOK b
ON s.BOOK_ID = b.BOOK_ID
WHERE s.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY b.CATEGORY
ORDER BY CATEGORY ASC;