SELECT
    COUNT(1) AS FISH_COUNT,
    MAX(LENGTH) AS MAX_LENGTH,
    FISH_TYPE
FROM (
    SELECT 
        ID,
        FISH_TYPE,
        (CASE
            WHEN LENGTH <= 10 OR LENGTH iS NULL THEN 10
            ELSE LENGTH
        END) AS LENGTH
    FROM FISH_INFO
) FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE ASC;